import Bottombar from "@/components/shared/Bottombar";
import Navbar from "@/components/shared/Navbar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <div className={inter.className}>
            <Toaster />
            <div className=" w-full max-w-6xl mx-auto flex flex-col">
              <Navbar />
              {children}
              <Bottombar />
            </div>
        </div>
  );
}

